### ISSUE TITLE
Embedded iframe

### ISSUE THREAD

**Issue by Johanna-hub** [fac-12/Little-Window#100]
Little Window needs to embedded in an iframe on the Chayn website

- [x] Test out embedding Little Window in a Siteground site
- [x] Write necessary code for Chayn to use in their site (else arrange meeting to do together)

**Comment by njseeto** [comment]
This code might work for embedding and styling:
`<iframe src='https://little-window.herokuapp.com' style='position: fixed; bottom: 0; right: 0; max-height: 90vh; z-index:1000; margin-top:6%'></iframe>`

**Comment by njseeto** [comment]
Currently available as a test site:
https://chayn.co/lw-test/
Password: littlewindowislearning
