### ISSUE TITLE
Mobile window: can't reopen once minimised

### ISSUE THREAD

**Issue by lucymk** [fac-12/Little-Window#184]
Once Little Window has been minimised on mobile, it's not possible to open it again (although the button is visible and clickable)

**Comment by matthewdking** [comment]
Option here could be to continually keep the ios and android nav bars continually open at the bottom of the screen.

[ios](https://stackoverflow.com/questions/33644584/how-might-one-force-show-the-mobile-safari-bottom-nav-bar-to-show-programmatical)

**Comment by lucymk** [comment]
also a relevant article I think https://www.eventbrite.com/engineering/mobile-safari-why/
