### ISSUE TITLE
Handle error from resource lookup

### ISSUE THREAD

**Issue by matthewdking** [fac-12/Little-Window#69]
The callback from the request to the google sheets resource in `userMessage.js` currently doesn't have an error branch.
```js
      request(url, (err, gsres, body) => {
        const resourceArray = JSON.parse(body).values.map(resource => ({
          text: resource[0],
          href: resource[1]
        }))
        data.resources = [...resourceArray]
        res.send(data)
      })
```
Consider adding an error branch and sending back some form of feedback to the user.

**Comment by matthewdking** [comment]
In addition a couple of lines later  you log the error message
```js
  requestdf.on('error', function (error) {
    console.log(error)
  })
```
We need to let the user know there has been an error from the request here.

**Comment by rb50** [comment]
Thanks!! We've now added DF error handling and Google Sheets (pull requests 115 and 116)
