### ISSUE TITLE
Save message conversationId

### ISSUE THREAD

**Issue by matthewdking** [fac-12/Little-Window#70]
I ran this a couple of times both in test and production and it doesn't seem to save the conversationId. The conversationId is blank or null in the message table. The subquery maybe isn't working?

It seems to work when I added quotes around the subquery...
```js
const saveMessage = (speech, conversationId) => {
  return db.query(
    `INSERT INTO messages (chat, conversation_id) VALUES ($1, '(SELECT id FROM conversation WHERE uniqueId = $2)')`,
    [speech, conversationId]
  )
}
```

**Comment by rb50** [comment]
This is only happening for the welcome messages before the user makes an input - this should be fine for now, we think this is ok as then unique ids are only stored for continuing conversations.
