### ISSUE TITLE
Dots sometimes remain on the screen

### ISSUE THREAD

**Issue by matthewdking** [fac-12/Little-Window#75]
I'm not sure how to reproduce this but sometimes the dots continually run after the bot has produced a message. Not overly important but just worth being aware of.
![dots](https://user-images.githubusercontent.com/25408167/37253175-0bca2e62-2526-11e8-801e-855bfd3c32d2.gif)

**Comment by matthewdking** [comment]
In fact I think #72 might fix this as it is sometimes when I'm typing that they continue to stay there but I'm not actually sure :man_shrugging:

**Comment by rb50** [comment]
Now fixed through #72
