### ISSUE TITLE
Calling saveConversation() with every new message 🤔

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/Little-Window#93]
I believe we are calling `saveConversation()` on our server every time we receive a new user message:

```
const userMessage = (req, res) => {
  const { speech } = req.body;
  apiaiCall(req, res, speech);
  saveConversation(req.body.uniqueId);
};
```

Can't remember if there was a good reason for doing this? Otherwise, it potentially puts unnecessary strain on our DB as we have to query it with every new message. Really it only needs to saveConversation() once at the beginning of a new conversation.

**Comment by rb50** [comment]
Good point! 😄 I think the reason was that the SaveConversation query checks if the uniqueID for the conversation already exists in the conversation table, and if not, adds it in, as we can't otherwise know if it's the first message?

**Comment by rb50** [comment]
Possibly we could only add the unique ID to the database when the 'Little Window Welcome' first message is sent - we could check the speech element of this message for this text
