### ISSUE TITLE
Emergency Intent

### ISSUE THREAD

**Issue by Johanna-hub** [fac-12/Little-Window#98]
Relates to #9 
- [ ] Little Window provides a response to keywords such as help, abuse, emergency danger

**Comment by jamiecoe** [comment]
I added all the danger words I could think of as entities on DF, then got about half way through making user-utterances for these in the emergency intent - this seemed to be a necessary step (although I'm not 100% sure).

**Comment by rb50** [comment]
Reviewed and tested, this seems to be working well, LW will be trained more through use and testing
