### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by Johanna-hub** [fac-12/Little-Window#99]
- [x] Chrome
- [x] Firefox
- [x] Safari - cannot submit different country name

**Comment by jamiecoe** [comment]
Kitty getting squished in Safari
- should be fixable by using `max-width` property for `Botmessage`, instead of `margin-left: 20%;`

Messages not autoscrolling for Firefox v56
- Maybe something to do with `scrollIntoView()` in `Conversation.js`

**Comment by rb50** [comment]
This seems to be fixed in terms of scrolling - very slightly more jumpy than other browsers but we'll see if it comes up in user testing
